; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
	-D DHT_ENABLE_RAW=1 
	-D AUTO_POWER_OFF_MS=5000

lib_deps = 
	asukiaaa/ST7032_asukiaaa@^1.0.5
	bertmelis/esp32DHT@^1.0.1
